Repository Dev-FE-1/Toy_Project_II_TEAM5, pull requests merged in 2024-08, with the labels that each got.

#18 Feat: 급여 지급 내역 컴포넌트 구현
  .eslintrc.cjs
  src/components/Navbar/Navbar.jsx
  src/index.css
  src/pages/salary-management/Payslip/PayrollAction.jsx
  src/pages/salary-management/Payslip/PayrollItem.jsx
  src/pages/salary-management/Payslip/PayrollTotal.jsx
  src/pages/salary-management/Payslip/Payslip.jsx
  src/pages/salary-management/Payslip/Payslip2.jsx
  src/pages/salary-management/salary-management-page.jsx
Labels: feature

#20 Feat: 일정관리 UI 구현
  src/pages/task-management/Schedule/Schedule.jsx
  src/pages/task-management/Schedule/ScheduleItem.jsx
  src/pages/task-management/Schedule/TimeContainer.jsx
  src/pages/task-management/taskManagement-page.jsx
Labels: feature

#24 Feat: 점심메뉴 UI 구현
  src/assets/lunch/koreanImage.png
  src/assets/lunch/westernImage.png
  src/pages/home/Lunch/Lunch.jsx
  src/pages/home/home-page.jsx
Labels: feature

#26 Feat: Header 컴포넌트 구현
  src/components/Header/Header.jsx
  src/pages/salary-management/salary-management-page.jsx
  src/pages/task-management/taskManagement-page.jsx
Labels: feature

#31 Feat: 파이어베이스 라우팅 설정 및 데이터 함수 구현
  jsconfig.json
  package-lock.json
  package.json
  src/App.jsx
  src/firebase/firebaseConfig.js
  src/hooks/useUser.jsx
  src/mock/addCommute.jsx
  src/mock/addEmployee.jsx
  src/mock/addProfile.jsx
  src/mock/data.js
  src/mock/fetchCommute.jsx
  src/mock/fetchEmployee.jsx
  src/pages/admin/admin-page.jsx
  src/pages/admin/login.jsx
  vite.config.js
Labels: feature

#35 [close: #34] Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#36 [#33] Feat: Footer UI 구현
  src/components/Footer/Footer.jsx
Labels: feature

#38 [#10] Feat: import ShadowyBox
  src/components/Schedule/Schedule.jsx
Labels: feature

#39 Feat: import ShadowyBox
  src/components/Payslip/Payslip.jsx
Labels: feature

#43 Feat: 오늘의 할 일 데이터베이스 구성 함수 셋팅
  src/components/List/ContentRow.jsx
  src/components/List/CustomRenderers/TodoChecklist.jsx
  src/components/List/ListComponent.jsx
  src/components/List/TodoList.jsx
  src/components/shared/ShadowyBox.jsx
  src/mock/fetchEmployeeTasks.jsx
Labels: feature

#45 Feat: 로그인 페이지 UI 수정 및 로그인/로그아웃 기능 구현
  src/App.jsx
  src/assets/icons/bg-pattern-bottom.svg
  src/assets/icons/bg-pattern-top.svg
  src/assets/icons/wave-left.svg
  src/assets/icons/wave-right.svg
  src/components/Navbar/UserStatus.jsx
  src/pages/signin/signin-page.jsx
Labels: feature

#46 Feat: 급여관리, 일정관리 페이지에 Footer 추가
  src/pages/home/home-page.jsx
  src/pages/salary-management/salary-management-page.jsx
  src/pages/task-management/taskManagement-page.jsx
Labels: feature

#54 Fix: 버튼 컴포넌트 DOM 에러 해결
  src/components/Payslip/CorrectionModalContents.jsx
  src/components/Payslip/CorrectionTrigger.jsx
  src/components/Payslip/PayrollAction.jsx
  src/components/Payslip/RequestModalContents.jsx
  src/components/Payslip/RequestTrigger.jsx
  src/components/shared/Button.jsx
Labels: feature

#64 Feat: 점심메뉴 UI 수정
  src/components/Lunch/Lunch.jsx
Labels: feature

#67 Feat: 업무관리 페이지 Redux Store에 데이터 패칭 액션 세팅 & 상태 관리
  package-lock.json
  package.json
  src/components/List/CustomRenderers/TodoChecklist.jsx
  src/components/List/EmployeeList.jsx
  src/components/List/TodoList.jsx
  src/components/Schedule/EditModalContents.jsx
  src/components/Schedule/ModalContents.jsx
  src/components/Schedule/Schedule.jsx
  src/components/Schedule/ScheduleItem.jsx
  src/components/Schedule/TimeContainer.jsx
  src/components/shared/Button.jsx
  src/components/shared/Loading.jsx
  src/components/shared/Modal.jsx
  src/mock/addEmployeeTasks.jsx
  src/mock/deleteEmployeeTasks.jsx
  src/mock/fetchEmployeeTasks.jsx
  src/mock/updateEmployeeTasks.jsx
  src/reducers/taskSlice.js
  src/store.js
Labels: feature

#68 Feat: 캘린더 컴포넌트를 리팩토링, 급여관리 페이지를 완성
  .gitignore
  jsconfig.json
  src/components/Calendar/Calendar-Days.jsx
  src/components/Calendar/Calendar-Navigation.jsx
  src/components/Calendar/Calendar-header.jsx
  src/components/Calendar/Calendar.jsx
  src/components/Calendar/Calendar.styled.jsx
  src/components/Calendar/Month-Selector.jsx
  src/components/Container/calendar-context.jsx
  src/components/Payslip/CorrectionModalContents.jsx
  src/components/Payslip/CorrectionTrigger.jsx
  src/components/Payslip/Payslip.jsx
  src/components/Payslip/RequestTrigger.jsx
  src/constants/calendar.js
  src/firebase/dataInserting.js
  src/hooks/useAttandance.jsx
  src/hooks/useCalendar.jsx
  src/pages/salary-management/ScheduleList.jsx
  src/pages/salary-management/salary-management-page.jsx
  src/pages/task-management/taskManagement-page.jsx
  src/reducers/salarySlice.js
  src/store.js
  src/styles/GlobalStyles.jsx
  src/utils/calcOverTime.js
  src/utils/isHoliday.js
  src/utils/setDateString.js
Labels: feature

#70 Feat: 홈 오늘의 할 일 페이지 Redux Store 데이터 패칭
  src/components/List/ContentRow.jsx
  src/components/List/CustomRenderers/EmployeePosition.jsx
  src/components/List/CustomRenderers/EmployeeProfile.jsx
  src/components/List/CustomRenderers/EmployeeStatus.jsx
  src/components/List/CustomRenderers/Progressbar.jsx
  src/components/List/CustomRenderers/TodoChecklist.jsx
  src/components/Schedule/Schedule.jsx
  src/hooks/useTodoList.jsx
Labels: feature

#73 Feat: 월별 데이터 컴포넌트에서 일별 분리
  package-lock.json
  package.json
  src/components/List/ContentRow.jsx
  src/components/Schedule/Schedule.jsx
  src/components/Schedule/TimeContainer.jsx
  src/hooks/useTodoList.jsx
  src/reducers/taskSlice.js
Labels: feature

#77 Fix: getDivisionColor 수정
  README.md
  src/components/List/CustomRenderers/TodoChecklist.jsx
  src/components/Schedule/EditModalContents.jsx
  src/components/Schedule/ModalContents.jsx
  src/components/Schedule/Schedule.jsx
Labels: feature

#80 Refactor: 일정 관리 리팩토링
  src/components/Calendar/Calendar-Days.jsx
  src/components/Calendar/Calendar.jsx
  src/components/Container/calendar-context.jsx
  src/components/Schedule/ModalContents.jsx
  src/components/Schedule/Schedule.jsx
  src/constants/Task.js
  src/hooks/useAuthState.jsx
  src/hooks/useTodoListForCalendar.jsx
  src/pages/task-management/TaskList.jsx
  src/pages/task-management/taskManagement-page.jsx
  src/reducers/taskSlice.js
Labels: feature

#88 Refactor: 코드 리뷰 피드백 반영 (원지)
  src/components/Constant/todos.jsx
  src/components/List/CustomRenderers/TodoChecklist.jsx
  src/components/List/EmployeeList.jsx
  src/components/List/TodoList.jsx
  src/components/Schedule/EditModalContents.jsx
  src/components/Schedule/ModalContents.jsx
  src/components/Schedule/Schedule.jsx
  src/components/shared/DateSelect.jsx
  src/constants/Employees.js
  src/constants/Keys.js
  src/hooks/useForm.jsx
  src/mock/addEmployeeTasks.jsx
  src/utils/getCompletionValue.js
  src/utils/getDateTime.js
Labels: refactor

#89 Refactor: 코드 리뷰 피드백 반영 (윤환)
  src/components/Login/LoginBanner.jsx
  src/components/Login/LoginForm.jsx
  src/hooks/useLogin.jsx
  src/pages/signin/signin-page.jsx
Labels: refactor

#90 Refactor: 코드 리뷰 피드백 반영 (원지)
  src/components/Schedule/EditModalContents.jsx
Labels: refactor

#91 Deploy: Merge code-review to main
  src/components/Constant/todos.jsx
  src/components/Footer/Footer.jsx
  src/components/List/CustomRenderers/TodoChecklist.jsx
  src/components/List/EmployeeList.jsx
  src/components/List/TodoList.jsx
  src/components/Login/LoginBanner.jsx
  src/components/Login/LoginForm.jsx
  src/components/Lunch/Lunch.jsx
  src/components/Navbar/UserStatus.jsx
  src/components/Payslip/CorrectionModalContents.jsx
  src/components/Payslip/Payslip.jsx
  src/components/Payslip/RequestModalContents.jsx
  src/components/Schedule/EditModalContents.jsx
  src/components/Schedule/ModalContents.jsx
  src/components/Schedule/Schedule.jsx
  src/components/shared/DateSelect.jsx
  src/components/shared/Layout.jsx
  src/constants/Employees.js
  src/constants/Keys.js
  src/hooks/useCurrentPath.jsx
  src/hooks/useForm.jsx
  src/hooks/useLogin.jsx
  src/mock/addEmployeeTasks.jsx
  src/pages/signin/signin-page.jsx
  src/utils/getCompletionValue.js
  src/utils/getDateTime.js
Labels: refactor

#92 Refactor: Login 페이지 이미지 경로 지정 방식 변경
  src/components/Login/LoginBanner.jsx
Labels: refactor
